### PR TITLE
CacheProducer

### PR DESCRIPTION
**Pull request by jpmediadev**
add CacheProducer for tick events

This is give 5X backtest performance (in theory) for repeatedly  (with same data) tests, but need 2x memory in the peek of processing (please see how the cleaning is implemented - maybe it is possible to do better)

Tried to implement yield + Pickled version   to reduce memory load, but the speed dropped dramatically...

```
Running backtest NO-CACHE...
2021-01-13T14:32:49.763Z [INF] BacktestEngine: =================================================================
...
2021-01-13T14:32:49.764Z [INF] BacktestEngine: Elapsed time:   0:00:19.749640
2021-01-13T14:32:49.764Z [INF] BacktestEngine: Execution resolution: BTC/USDT.BINANCE=TICK
2021-01-13T14:32:49.764Z [INF] BacktestEngine: Iterations: 2,206,988
2021-01-13T14:32:49.764Z [INF] BacktestEngine: Total events: 321
2021-01-13T14:32:49.765Z [INF] BacktestEngine: Total orders: 64
2021-01-13T14:32:49.765Z [INF] BacktestEngine: Total positions: 32
```

```
Running backtest WITH CACHE...
2021-01-13T14:38:01.108Z [INF] BacktestEngine: =================================================================
...
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Elapsed time:   0:00:03.835234
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Execution resolution: BTC/USDT.BINANCE=TICK
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Iterations: 2,206,988
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Total events: 321
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Total orders: 64
2021-01-13T14:38:01.109Z [INF] BacktestEngine: Total positions: 32
```

the problem occurred while trying to re-execute self.engine.run(strategies=[strategy])

```
error:
  File "nautilus_trader/backtest/engine.pyx", line 449, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader/backtest/engine.pyx", line 510, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader/backtest/engine.pyx", line 402, in nautilus_trader.backtest.engine.BacktestEngine.reset
  File "nautilus_trader/common/component.pyx", line 265, in nautilus_trader.common.component.Component.reset
  File "nautilus_trader/common/component.pyx", line 308, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/common/component.pyx", line 305, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/core/fsm.pyx", line 117, in nautilus_trader.core.fsm.FiniteStateMachine.trigger
nautilus_trader.core.fsm.InvalidStateTrigger: RUNNING -> RESET

```
didn’t go deep because these are system design issues, I will be happy if  it will be possible to use it, the value in speeding up backtests for everyone is obvious.

### CODE REVIEW

**Comment by cjdsellers** [comment]
It might be a good idea to take a fresh branch though its picking up alot of old commits?

I'll see whats going on with the reset at my end.

**Comment by cjdsellers** [comment]
Ah, it was just where you where calling `_create_tick_cache`. It just needed to be at the top of the `setup` rather than at the end of the constructor. 

I'll push a cleaned up version soon.

**Comment by jpmediadev** [comment]
sorry for the non-obvious code.
self._producer.setup(self.min_timestamp, self.max_timestamp) was called  inside _create_tick_cache 
to create pre-cached ticks before using in engine
I tried to change your code as little as possible and use it inside

**Comment by cjdsellers** [comment]
That's a good approach. It was nice the way you used a facade pattern which is sort of a proxy for interfaces in this language which doesn't really support them directly. You also maintained the current code style for doing so too which is appreciated.

**Comment by jpmediadev** [comment]
Thanks Christopher, it's a pleasure to write code with you :)

**Pull request merged**
