### PR TITLE
Refactor Bybit trade schema and improve websocket reconnects

### PR DESCRIPTION
**Pull request by davidsblom**
# Pull Request

Refactor the data schema for the trade message using optional fields for futures and option messages.

Resubscribe to all subscription feeds when reconnecting. 

## Type of change

Delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How has this change been tested?

pre-commit and locally subscribing to the trade and quote ticks.

### CODE REVIEW

**Comment by cjdsellers** [comment]
Hey David,

Good stuff, just on mobile but checkout the websocket client base L213 - I believe the pings are handled by the Rust websocket base client and configured for 20 seconds there.

**Comment by cjdsellers** [comment]
Also a quick tip, to see more websocket logs - in the `LoggingConfig` set `use_pyo3=True` and also set the `RUST_LOG` env var to `debug`:

```
export RUST_LOG=debug
```

**Comment by davidsblom** [comment]
Thanks for the tips! I'll remove the ping messages.

**Comment by davidsblom** [comment]
Made the changes and also added to resubscribe to the data feeds when reconnecting

**Pull request merged**
