### PR TITLE
Betfair patches

### PR DESCRIPTION
**Pull request by limx0**
This PR fixes some bugs primarily in the Betfair data client.
- Add a sleep in betfair data client when subscribing to markets to allow all strategies to send through subscription messages
- Fix market data subscription replacing existing subscription when subscribing to multiple markets 
- Minor refactor of trade tick parsing logic (DRY)
- Remove strategy_id from `customer_order_ref` which has a limited size and strict character requirements.
- Don't cpdef variables

It may also solve https://github.com/nautechsystems/nautilus_trader/issues/257#issuecomment-822198782?

### CODE REVIEW

**Comment by ian-wazowski** [comment]
@limx0 

I think your fetch solve the [comment](https://github.com/nautechsystems/nautilus_trader/issues/257#issuecomment-822198782)

**Comment by limx0** [comment]
@cjdsellers unsure why the 3.7 build is failing here - any ideas?

**Comment by cjdsellers** [comment]
Windows with Python 3.9 tests intermittent on:
```
ERROR  - ModuleNotFoundError: No module named 'nautilus_trader.model.enums'
ERROR  - ModuleNotFoundError: No module named 'nautilus_trader.model.enums'
```

Merging.

**Comment by cjdsellers** [comment]
```
tests\integration_tests\adapters\betfair\conftest.py:3: in <module>
    from nautilus_trader.adapters.betfair.common import BETFAIR_VENUE
nautilus_trader\adapters\betfair\common.py:18: in <module>
    from nautilus_trader.model.enums import OrderSide
E   ModuleNotFoundError: No module named 'nautilus_trader.model.enums'
```

**Pull request merged**
