### PR TITLE
Improve sandbox by adding account settings to the SandboxExecutionCli…

### PR DESCRIPTION
**Pull request by davidsblom**
…entConfig

# Pull Request

Add account type, default leverage and oms type to the sandbox execution client config.

## Type of change

Delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How has this change been tested?

Locally running the sandbox with Bybit data

### CODE REVIEW

**Comment by cjdsellers** [comment]
Thanks @davidsblom

I haven't looked too closely here yet, but would this address https://github.com/nautechsystems/nautilus_trader/issues/1657 as well?

**Comment by davidsblom** [comment]
I think so. Haven't tested with cash account though.

**Comment by VeraLyu** [comment]
Could we add multiple base currency support (like I have "BTC", "ETH" all in my margin account)as well? as some scenarios strategy may involve multiple currency arbitrary.

**Comment by davidsblom** [comment]
Yes indeed. It is probably just updating the config types (could be wrong).

**Comment by cjdsellers** [comment]
I'll make a breaking change for the config tomorrow to head more towards the backtest venue config, including multiple starting currencies.

**Comment by davidsblom** [comment]
Awesome! 👍

**Comment by VeraLyu** [comment]
Tested with binance, and it failed with creating executing client, it worked in previous version:
my code:
            exec_clients={
            "SANDBOX": SandboxExecutionClientConfig(
                    venue="BINANCE",
                    currency="USDC",
                    balance=10_000_000,
                    default_leverage=10.0,
                    oms_type="NETTING",
                    account_type="MARGIN",
            ),
        },


  
File "/home/ubuntu/crypto_level2/nautilus_trader/./examples/live/binance/binance_trader_with_controller.py", line 188, in <module>
    node = asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/crypto_level2/nautilus_trader/./examples/live/binance/binance_trader_with_controller.py", line 175, in main
    node.build()
  File "/home/ubuntu/crypto_level2/nautilus_trader/nautilus_trader/live/node.py", line 263, in build
    self._builder.build_exec_clients(self._config.exec_clients)
  File "/home/ubuntu/crypto_level2/nautilus_trader/nautilus_trader/live/node_builder.py", line 247, in build_exec_clients
    client = factory.create(**factory_kws)
  File "/home/ubuntu/crypto_level2/nautilus_trader/nautilus_trader/adapters/sandbox/factory.py", line 70, in create
    exec_client = SandboxExecutionClient(
  File "/home/ubuntu/crypto_level2/nautilus_trader/nautilus_trader/adapters/sandbox/execution.py", line 111, in __init__
    self.exchange = SimulatedExchange(
  File "nautilus_trader/backtest/exchange.pyx", line 224, in nautilus_trader.backtest.exchange.SimulatedExchange.__init__
    self.add_instrument(instrument)
  File "nautilus_trader/backtest/exchange.pyx", line 320, in nautilus_trader.backtest.exchange.SimulatedExchange.add_instrument
    Condition.equal(instrument.id.venue, self.id, "instrument.id.venue", "self.id")
  File "nautilus_trader/core/correctness.pyx", line 306, in nautilus_trader.core.correctness.Condition.equal
    raise make_exception(
ValueError: The 'instrument.id.venue' <class 'nautilus_trader.model.identifiers.Venue'> of BINANCE was not equal to the 'self.id' <class 'nautilus_trader.model.identifiers.Venue'> of SANDBOX

**Comment by cjdsellers** [comment]
Pushed up a bunch of changes to the config aligning more closely with the `BacktestVenueConfig`.

**Comment by VeraLyu** [comment]
> Pushed up a bunch of changes to the config aligning more closely with the `BacktestVenueConfig`.

Hi Chris,
May I ask on which branch do these changes go? Do they include multi-currency support?

Thanks

**Comment by cjdsellers** [comment]
Hey @VeraLyu

All changes will first go to `develop` branch. [Here's](https://github.com/nautechsystems/nautilus_trader/commit/54d05103b79c2859a5b8efe1847627fee1a716fc) the commit I was referring to above.

Multi-currency accounts with multiple starting balances are now supported for Sandbox too.

**Pull request merged**
