### PR TITLE
Fix IB contract ID dict

### PR DESCRIPTION
**Pull request by niks199**
# Pull Request

Related to this issue:
https://github.com/nautechsystems/nautilus_trader/issues/706

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested?

Tested locally

### CODE REVIEW

**Comment by niks199** [comment]
@limx0 please have a look.

**Comment by limx0** [comment]
LGTM, thanks @niks199 !

**Comment by cjdsellers** [comment]
Hey @niks199 thanks once more!

Just two failures on that last CI run:
```
=================================== FAILURES ===================================
____________ TestInteractiveBrokersData.test_subscribe_trade_ticks _____________
self = <tests.integration_tests.adapters.interactive_brokers.test_data.TestInteractiveBrokersData object at 0x128507b80>
event_loop = <uvloop.Loop running=False closed=False debug=False>
    @pytest.mark.asyncio
    async def test_subscribe_trade_ticks(self, event_loop):
        # Arrange
        instrument_aapl = IBTestStubs.instrument(symbol="AAPL")
        self.data_client.instrument_provider.contract_details[
            instrument_aapl.id
        ] = IBTestStubs.contract_details("AAPL")
        # Act
        with patch.object(self.data_client, "_client") as mock:
>           self.data_client.subscribe_trade_ticks(instrument_id=instrument_aapl.id)
tests/integration_tests/adapters/interactive_brokers/test_data.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = InteractiveBrokersDataClient-InteractiveBrokers
instrument_id = InstrumentId('AAPL.NASDAQ')
    def subscribe_trade_ticks(self, instrument_id: InstrumentId):
>       contract_details: ContractDetails = self._instrument_provider.contract_details[
            instrument_id.value
        ]
E       KeyError: 'AAPL.NASDAQ'
nautilus_trader/adapters/interactive_brokers/data.py:170: KeyError
---------------------------- Captured stdout setup -----------------------------
2022-07-23T06:38:33.758664032Z [INF] TRADER-000.MockCacheDatabase: INITIALIZED.
2022-07-23T06:38:33.758736485Z [INF] TRADER-000.Cache: INITIALIZED.
2022-07-23T06:38:33.759687629Z [INF] TRADER-000.InteractiveBrokersDataClient: INITIALIZED.
2022-07-23T06:38:33.760632087Z [INF] TRADER-000.ExecClient-InteractiveBrokers: INITIALIZED.
_________ TestInteractiveBrokersData.test_subscribe_order_book_deltas __________
self = <tests.integration_tests.adapters.interactive_brokers.test_data.TestInteractiveBrokersData object at 0x128507e80>
event_loop = <uvloop.Loop running=False closed=False debug=False>
    @pytest.mark.asyncio
    async def test_subscribe_order_book_deltas(self, event_loop):
        # Arrange
        instrument = IBTestStubs.instrument(symbol="AAPL")
        self.instrument_setup(instrument, IBTestStubs.contract_details("AAPL"))
        # Act
        with patch.object(self.data_client, "_client") as mock:
>           self.data_client.subscribe_order_book_snapshots(
                instrument_id=instrument.id, book_type=BookType.L2_MBP
            )
tests/integration_tests/adapters/interactive_brokers/test_data.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nautilus_trader/adapters/interactive_brokers/data.py:152: in subscribe_order_book_snapshots
    return self._request_market_depth(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = InteractiveBrokersDataClient-InteractiveBrokers
instrument_id = InstrumentId('AAPL.NASDAQ')
handler = <bound method InteractiveBrokersDataClient._on_order_book_snapshot of InteractiveBrokersDataClient-InteractiveBrokers>
depth = 5
    def _request_market_depth(self, instrument_id: InstrumentId, handler: Callable, depth: int = 5):
>       contract_details: ContractDetails = self._instrument_provider.contract_details[
            instrument_id.value
        ]
E       KeyError: 'AAPL.NASDAQ'
nautilus_trader/adapters/interactive_brokers/data.py:225: KeyError
```

**Comment by cjdsellers** [comment]
Great CI passes, looks like you just need to sign the CLA

**Comment by niks199** [comment]
@cjdsellers I do not understand why cla status is still pending. it was signed already.

**Comment by cjdsellers** [comment]
I think what it may be is I saw two different usernames where commits came from. Will merge for now.

**Pull request merged**
