### PR TITLE
IB Refactor v2

### PR DESCRIPTION
**Pull request by rsmb7z**
Hi,
In regards to #987, mostly things done. Bit of refinement and adding of tests pending.

### Breaking Changes
* Added `InteractiveBrokersInstrumentProviderConfig` for `InteractiveBrokersDataClient` and `InteractiveBrokersExecutionClient`
* Added `InteractiveBrokersGatewayConfig` to remove ambiguity, for gateway specific config
* `filters` no longer used due to ambiguity, as each contract needed to be specified explicitly and causing ambiguity. Replaced with `load_contracts`

### Enhancements
* InstrumentId can be used to load Instruments. Use `load_ids` in `InteractiveBrokersInstrumentProviderConfig` to load many instruments
* `load_contracts` can be used `InteractiveBrokersInstrumentProvider` to load instrument using `IBContract`
* Removed configuration impact of `load_all` as it will never load all in `InteractiveBrokers` case
* Added `build_options_chain`, `build_futures_chain`, `min_expiry_days`, `max_expiry_days` to the `InteractiveBrokersInstrumentProviderConfig` to allow load multiple related contracts for all in `load_ids` and `load_contracts`. Same parameters available in `IBContract` which, if specified, will override the global config 
* Added support for `MARKET_TO_LIMIT`, `MARKET_IF_TOUCHED`, `LIMIT_IF_TOUCHED`, `STOP_MARKET`, `STOP_LIMIT`, `TRAILING_STOP_MARKET`, `TRAILING_STOP_LIMIT`
* Added support for `TimeInForce` includes `DAY`, `GTC`, `IOC`, `GTD`, `AT_THE_OPEN`, `FOK`
* Added support for `OrderList` allowing to submit any combination from Strategy i.e. BracketOrders, EntryWithStop, EntryWithTrailingStop, OCA, AllOrNone etc
* Added support for `WhatIf` analysis using `Order.tags`. `WhatIf` simulation order response from `InteractiveBrokers` will be returned in Order Rejection reason
* Instrument can be requested from within Strategy without the need to load explicitly on Node start
* Moved env `TWS_USERNAME` and `TWS_PASSWORD` to gateway module so not to make env values part of `DataClientConfig` or `ExecClientConfig`
* Added `market_data_type` in `InteractiveBrokersDataClientConfig` to allow request for `DELAYED` and `FROZEN` data (useful for accounts without data subscription i.e Demo)
* Added `use_regular_trading_hours` in `InteractiveBrokersDataClientConfig` for Data requests
* Multiple `DataClient` registration possible, useful for sourcing from different userids
* Added 'OrderStatusReports` and `PositionStatusReports`

### Usage Instruction:

- Build and install IBAPI from https://interactivebrokers.github.io/
- IB TWS/Gateway v10.19 or latest
- Run `examples/live/interactive_brokers_example.py`
- Feel free to report any error or issues

### CODE REVIEW

**Comment by Troubladore** [comment]
@rsmb7z - thanks for submitting this pull request. When I built using this version, and tried to run the legacy code example "interactive_brokers_example.py" from the nautilus repo, I got an error: "ModuleNotFoundError: No module named 'ibapi'"

Since you're using the IBAPI library, does there need to be a line like the following added to the project .toml to support v2 of the adapter?
[tools.poetry.dependencies]
ibapi = { git = "https://interactivebrokers.github.io/??", branch = "???" }

I was able to get it working by running the setup command targeting my repo's .venv, but I don't think that will be sustainable from a poetry perspective within Nautilus

**Comment by rsmb7z** [comment]
> Since you're using the IBAPI library, does there need to be a line like the following added to the project .toml to support v2 of the adapter?

IB don't publish anymore on PyPI so it wouldn't install using `pip`. You have to build from source from the provided link. Execute below from the `ibapi` source folder for build and install.
```
python setup.py sdist
pip install dist/ibapi-10.19.1.tar.gz
```

> @rsmb7z - thanks for submitting this pull request. When I built using this version, and tried to run the legacy code example "interactive_brokers_example.py" from the nautilus repo, I got an error: "ModuleNotFoundError: No module named 'ibapi'"

Use the example from this PR branch located at same path as there are some breaking changes.

**Comment by Troubladore** [comment]
@rsmb7z - Can you clarify the relationship between "sdist" in the build, and "dist" in the install instructions you referenced? I'm thinking some or all of these action might be scriptable within the .toml, and I'd like to experiment.

Also, we did see the updated example from the PR, and it worked in our initial testing.

**Comment by rsmb7z** [comment]
> @rsmb7z - Can you clarify the relationship between "sdist" in the build, and "dist" in the install instructions you referenced? I'm thinking some or all of these action might be scriptable within the .toml, and I'd like to experiment.

@Troubladore I don't know much on the builds however just like any Python program it should be able to build or make wheel. This works for me so I am using as below to automate install on linux using script. However if someone can make it installable using Poetry would definetly me more convinient.
```
ibapi_filename=twsapi_macunix.1019.01.zip
ibapi_whl=ibapi-10.19.1-py3-none-any.whl
home_path=/home/ubuntu
cd $home_path && curl -O https://interactivebrokers.github.io/downloads/$ibapi_filename
cd $home_path && unzip -o $ibapi_filename -d $home_path
cd $home_path/IBJts/source/pythonclient && python3 setup.py bdist_wheel
pip install $home_path/IBJts/source/pythonclient/dist/$ibapi_whl
```

> Also, we did see the updated example from the PR, and it worked in our initial testing.

That's great. Although major part is done and writing tests/examples is pending, just caution though to use in Paper Trading account.

**Comment by martinsaip** [comment]
> > Also, we did see the updated example from the PR, and it worked in our initial testing.
> 
> That's great. Although major part is done and writing tests/examples is pending, just caution though to use in Paper Trading account.

Way to go @rsmb7z ! 👍🏾 🥇 
A final version of this refactor should contain that subroutine which automatically chooses the correct IBKR API ports for production and paper accounts according to an account used, as well as software used: TWS's production port is 7496 and paper port is now 7497. These ports are automatically assigned when TWS is installed or reinstalled.
However, IB Gateway's default paper port is **4002, leaving 4001 for the production version.**

**Comment by rsmb7z** [comment]
Hi @martinsaip 
> A final version of this refactor should contain that subroutine which automatically chooses the correct IBKR API ports for production and paper accounts according to an account used, as well as software used: TWS's production port is 7496 and paper port is now 7497.

It is intentionaly default to None so user have to specify the port explicitly if the Docker Image (gateway auto start) is not being used. This is based on following scenarios:

- Although default setting, these ports are not strictly applies to paper/live account. Saving TWS layout settings and restoring from live to paper or vice versa would copy the port settings as well. Hence more chances of error.
- You don't have to specify the port number when you use Docker Image for gateway, because in this case Image being pulled with default settings it can select the port based on paper/live account

Furthermore now it support running multiple Docker images on same machine or virtual instance when you specify the port number (of your choice). Say 4001 for one IB Gateway instance, and 4002 for another IB Gateway instance, this can be live and/or paper with any combination, though using different Nautilus Instance for each gateway connection.

**Comment by cjdsellers** [comment]
Looks like just some mypy errors if you run the `pre-commit`:

```
nautilus_trader/adapters/interactive_brokers/client/common.py:54: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
nautilus_trader/adapters/interactive_brokers/client/common.py:55: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
nautilus_trader/adapters/interactive_brokers/client/common.py:56: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
nautilus_trader/adapters/interactive_brokers/client/common.py:108: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
nautilus_trader/adapters/interactive_brokers/client/common.py:152: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
nautilus_trader/adapters/interactive_brokers/client/common.py:153: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
tests/integration_tests/adapters/interactive_brokers/test_client.py:64: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
tests/integration_tests/adapters/interactive_brokers/responses/generate_test_data.py:48: error: Missing positional arguments "cache", "clock", "logger" in call to "get_cached_ib_client"  [call-arg]
tests/integration_tests/adapters/interactive_brokers/responses/generate_test_data.py:48: error: Argument 1 to "get_cached_ib_client" has incompatible type "str"; expected "AbstractEventLoop"  [arg-type]
tests/integration_tests/adapters/interactive_brokers/responses/generate_test_data.py:59: error: Missing positional arguments "cache", "clock", "logger" in call to "get_cached_ib_client"  [call-arg]
tests/integration_tests/adapters/interactive_brokers/responses/generate_test_data.py:59: error: Argument 1 to "get_cached_ib_client" has incompatible type "str"; expected "AbstractEventLoop"  [arg-type]
Found 4 errors in 1 file (checked 565 source files)
```

**Comment by cjdsellers** [comment]
Great work @rsmb7z :clap: 

I'm going to merge this where we are here, even though macos CI is failing - that has something to do with our own adapter mocks which are in the process of being reimplemented anyway.

Thank you for this amazing contribution :pray:

**Pull request merged**
