### PR TITLE
Implement TA-Lib Integration

### PR DESCRIPTION
**Pull request by rsmb7z**
# Pull Request

Enables straightforward integration of TA-Lib into strategies. Useful for anyone looking to utilize TA-Lib indicators.

## Type of change
- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by cjdsellers** [comment]
Thanks so much @rsmb7z

This has been a highly requested feature for years.

I'm thinking this will be a bit of a hit to test coverage for the files under the `indicators` subpackage though. I wonder if there's some basic smoke tests we can setup to exercise a reasonable amount of the code? We don't have to fully exhaust every edge case, even if that would be the ideal.

Thoughts?

**Comment by rsmb7z** [comment]
Hi @cjdsellers 
Without a doubt, rigorous validation tests are crucial for ensuring quality and reliability. I'm currently developing tests for personal use, but I'd be more than happy to share them. To ensure they work seamlessly in a Continuous Integration (CI) environment, here are the necessary steps:

1. **Integration with Poetry**: TA-Lib can be added as a dependency in the Poetry configuration by inserting `ta-lib = "^0.4.28"` into the pyproject.toml file. It should be noted that the package name differs from the importing syntax, where `import talib` is used in the Python code.
2. **Installing the TA-Lib C Library**: The installation process on Windows presents certain challenges, and while automation is possible, a ready-made script for it is not currently available. For Linux systems, however, the following script has been effective. It facilitates the installation of the TA-Lib C Library, ensuring smooth operation of tests on Linux-based Continuous Integration (CI) systems:

    ```bash
    cd /home/ubuntu && wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    cd /home/ubuntu && tar -xzf ta-lib-0.4.0-src.tar.gz
    cd /home/ubuntu/ta-lib/ && ./configure --build=$(uname -i)-unknown-linux-gnu --prefix=/usr && make && sudo make install
    ```

    **Note**: This script is provided as is. Feel free to modify it or adjust the directory paths as needed for your CI environment.

By following these steps, we should be able to integrate TA-Lib into our CI pipeline effectively. If there are any specific requirements or constraints in our CI setup, please let me know, and I can adjust the approach accordingly.

**Comment by cjdsellers** [comment]
Yes, I think we'll need to add `ta-lib` as an optional dependency, I could sort this out post merge and we could do a follow up diff to add tests?

**Comment by rsmb7z** [comment]
> Yes, I think we'll need to add `ta-lib` as an optional dependency, I could sort this out post merge and we could do a follow up diff to add tests?

Sounds perfect.

**Review by cjdsellers — APPROVED** [review]

**Comment by cjdsellers** [comment]
Given the dependency on the binary too, and the fact this is an optional install - I'm happy if the tests just run on Linux too.

**Pull request merged**
