### PR TITLE
Add CSCV tools

### PR DESCRIPTION
**Pull request by graceyangfan**
# Pull Request

Add CSCV tools. #834 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested?

A notebook with EMACrossTrailingStop Strategy example is provided.

### CODE REVIEW

**Comment by cjdsellers** [comment]
Hi @graceyangfan 

Thanks for this, looks like we just need a pre-commit run over it:
```
pre-commit install
pre-commit run --all-files
```
:pray:

**Comment by cjdsellers** [comment]
Thanks for running the pre-commit

I've been deliberating over whether we should merge this PR. It's very well implemented (without me verifying the algorithms), however I feel it's tending to move out of scope for the main `nautilus_trader` project/repo. If it were a simpler more generic portfolio statistic then it might be OK.

This probably deserves to be part of a separate repository more focused on analysis and ML, which isn't something I currently have the capacity to setup.

So I'm happy if we leave this PR open for now in case things change, and to provide the resource for others?

**Comment by graceyangfan** [comment]
I am not sure where to place it，the main reason I add this is that nautilus_trader provide great fast backtesting but lack of tools to analysis the backrest results especially for parameters selection.

**Comment by Troubladore** [comment]
@graceyangfan - we deeply appreciate this contribution, and share your interest. As we look to implement more ML-based strategies, perhaps we can collaborate on a sibling repo that acts as a Nautilus add-on?

**Comment by cjdsellers** [comment]
> I am not sure where to place it，the main reason I add this is that nautilus_trader provide great fast backtesting but lack of tools to analysis the backrest results especially for parameters selection and evaluation.I want to add some tools for helping users with their strategies development.

I totally agree that this is a valuable addition, we just need to decide where best to place it.

**Pull request closed without merging**
