### PR TITLE
Improve request_bars function for Binance

### PR DESCRIPTION
**Pull request by graceyangfan**
# Pull Request
#693 
1.Allow users to call request_bars to get more than 1000 EXTERNAL bars limit.
2.The `on_bar `function will perform for historical bars and living bars. A symbol `is_historical_bar` is adding to Strategy class to distinguish if current bar is a historical bar.

## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this change been tested?
A new stratgy in request_history_bars.py and a live example binance_history_bars_testnet.py is used to test.More test will be added.

### CODE REVIEW

**Comment by cjdsellers** [comment]
Hi @graceyangfan 

Thanks for your work here. I reviewed the diff several times and just have two questions:
- I can't see anywhere the data engine refers to the `on_preprocess_bars` method? Did you intend on doing another diff to wire this up?
- I see for the partial bar you changed the code from popping from the list of bars to just indexing at `[-1]`. I'm not sure this is a good change because in this case a partially formed bar would be added to the cache, and be passed through logic which expects a closed bar as per its `BarType` spec. Thoughts here?

One slight preference I would have also is changing the method name to `on_bar_preprocess` just to highlight it relates to bars and keeps it nicely grouped visually with `on_bar`.

**Comment by graceyangfan** [comment]
@cjdsellers The logical of the data processing is:(1)request history bars,history bars  are sending into `on_preprocess_bars` to make some preprocess on bars , and process some registered nautilus indicators (2)after history bars,living bars are sending into `on_preprocess_bars`  to make some preprocess on bars,then nautilus_trader inside indicators compute,then on_bar where to create signals  for buying or selling.So `on_preprocess_bars` is just the same as nautilus_trader inside indicators,it need history bars to initialization and it need to perform both for history bars and living bars, nautilus_trader inside indicators is automatically, but it is only used for one bar_type. on_bar is only used for living bars.This is the difference.Of course,we could change on_bar to deal history bars and living bars and drop `on_preprocess_bars`  function.The rease I include the partial bar  is during my test I find that if I drop it,there will lose one bar between history bars and living bars in the end of history bars,maybe I need more test to confirm it.

**Comment by cjdsellers** [comment]
I think rather than adding another method into the project, you could handle this by writing some logic in the strategy as per the suggestion in Discord https://discord.com/channels/924497682343550976/924499913386102834/1010423470443724820

On the arrival of each bar, check if you're initialized, if not, check for the existence of cached bars, if they are there then you can perform any preprocessing or other computation you like. The only difference here is that this occurs in the existing `on_bar` method, rather than adding another one into the platform (which then has some asymmetry as wouldn't we need to add a preprocess to every other data type which can include historical objects?)

**Comment by graceyangfan** [comment]
@cjdsellers  As your suggestion,I will move on_bar to perform history data  like this: 
`
    def on_bar(self, bar: Bar, is_historical = False):
          if is_historical:
              do something 
          else:
              do something 
`

**Comment by graceyangfan** [comment]
@cjdsellers As your suggestion,I will move on_bar to perform history data like this:
```
    def on_bar(self, bar: Bar, is_historical: bool = False):
          do something (for history bars and living bars preprocessing) 
          
          if is_historical:
             return 
          # just for living trading 
          do something to generate trading siginals 
```
This looks much better, but lots of examples and codes need to correct where has on_bar function.
Or something like this:
```
    def on_bar(self, bar: Bar):
          do something (for history bars and living bars preprocessing) 
          
          if self.is_historical_bar:
             return 
          # just for living trading 
          do something to generate trading siginals 
```
`is_historical_bar` adding to Strategy class

**Comment by cjdsellers** [comment]
Were you able to write the logic you needed into the new `on_historical_data` method?

**Comment by graceyangfan** [comment]
> Were you able to write the logic you needed into the new `on_historical_data` method?

@cjdsellers It is enough!I will do this at this  weekend!

**Comment by cjdsellers** [comment]
Apologies, I could have phrased the question more clearly. Is the new functionality sufficient that we can now close this PR?

**Comment by graceyangfan** [comment]
@cjdsellers Accurately,I have made improve to request_bars with several request to get external bars  more than 1000,but binance did not provide more data for tick data,so it's difficult to make request_ticks work as I expect,maybe in the future we need to reuqest from a database or stream from other data provider,but that's a another topic.

**Pull request closed without merging**
