### PR TITLE
Added GenericBar and options for HV/IV

### PR DESCRIPTION
**Pull request by rsmb7z**
Fulfills requirement for #970.

### CODE REVIEW

**Comment by cjdsellers** [comment]
Hi @rsmb7z 

For this one, I'm feeling like `HistoricalVolatility` and `ImpliedVolatility` are more like `BarAggregation` types than price types?

I think we can consider the current `Bar` object as a "price bar", as the OHLC are of type `Price`. We could introduce this `GenericBar` and for the moment keep the OHLC as `Decimal` as you've done.

I don't think its going to work declaring those types as a C `double` though, I would just keep this in Python similar to the `BinanceBar`, however inherit from `Data`:
```python
GenericBar(Data):
    ...
```

Which avoids us having to define a new type of bar every time we want to represent some OHLCV bar aggregation with decimal as the OHLC types.

Then, it depends where we intend on forming these bars as to whether we want to append these members to `BarAggregation` or potentially create a `GenericBarAggregation` to separate the price based bars, from generic bars?

If we don't intend on sending volatility updates as a separate data type into the system and having the `DataEngine` build these bars, then it may be best just defining a `GenericBarAggregation` enum? although having said that, things will only work with the current `BarType` if we add these to `BarAggregation`.

My guess is you intend to write some custom code to form these bars, and _then_ send those back to the `DataEngine` for publishing on the message bus?

**Comment by rsmb7z** [comment]
Hi @cjdsellers 

> For this one, I'm feeling like `HistoricalVolatility` and `ImpliedVolatility` are more like `BarAggregation` types than price types?

These two are indeed replacement of `PriceType` in the `BarSpecification` whereas `BarAggregation` remains as is, which means these two types can have OHLC bar of any timeframe. In terms of OHLC values only difference is the Price and Percentage. That's why I have included these in the `PriceType` enum.

Following is the example snap:

image

*One thing important though, we should keep single `BarType` to keep things simpler and we can easily identify which class i.e Bar, GenericBar etc to use based on type and vice versa. However creating different `BarType` to accomodate the `BarSpecification` (`HistoricalVolatility` and `ImpliedVolatility`) may overly complicate the usage. In worst case there is no good alternative to accomodate for the `HistoricalVolatility` and `ImpliedVolatility` enum, we can keep in the `PriceType` as-is.*

> I don't think its going to work declaring those types as a C `double` though, I would just keep this in Python similar to the `BinanceBar`, however inherit from `Data`:
> Which avoids us having to define a new type of bar every time we want to represent some OHLCV bar aggregation with decimal as the OHLC types.

I tried using `Decimal` originally but that didn't worked because not supported in cython, yes we can use Python instead. You are right having `GenericBar(Data)` with Decimal will provide this to be used directly as well base class for any other sort of OHLC.

> If we don't intend on sending volatility updates as a separate data type into the system and having the `DataEngine` build these bars, then it may be best just defining a `GenericBarAggregation` enum? although having said that, things will only work with the current `BarType` if we add these to `BarAggregation`.

I think this is related to first question. `BarAggregation` of this bar and the original `Bar` have no difference. If we add these to `BarAggregation` enum we will loose the aggregation. Please have a look at following links:
https://interactivebrokers.github.io/tws-api/historical_bars.html
https://interactivebrokers.github.io/tws-api/tick_types.html

> My guess is you intend to write some custom code to form these bars, and _then_ send those back to the `DataEngine` for publishing on the message bus?

Yes correct. Will just flow like standard `Bar` where it will be consumed by Indicators and Strategy for decision making, and actions. Either loaded to the `DataEngine` for Backtesting or subscribed from the Live Broker in case of Live trading.

**Comment by cjdsellers** [comment]
Thanks for providing the examples and references from the IB docs.

I can see that with the way you're using `PriceType`, it does fit quite conveniently into the `BarType`.

Is it logical that we might be aggregating the volatility of the `BID`, `ASK,`, `MID`, `LAST` prices though? in which case the logical bar type becomes something like.

`ABC-IMPLIED-VOLATILITY.NYSE-1-MINUTE-LAST-EXTERNAL` (assuming these are actually being aggregated externally by IB)?

If we extended the `PriceType` then it opens up many code paths to error with the way its used throughout the core of the codebase. Or at least every 'switch' statement would have to be checked that its handling the invalid type cases (which would nearly always include these volatility types as being invalid).

**Comment by rsmb7z** [comment]
> Is it logical that we might be aggregating the volatility of the `BID`, `ASK,`, `MID`, `LAST` prices though? in which case the logical bar type becomes something like.

The volatility values are of the instrument so are complete in itself `HistoricalVolatility` and `ImpliedVolatility` whereas within BarType `BID`, `ASK,`, `MID`, `LAST` would always mean that it is `Price`. The scenario you are referring will be for the case of `Yield` which applies for Bonds. In that case enums for that will be added seperately such as `YieldBid`, `YieldAsk,`, `YieldLast`.


> `ABC-IMPLIED-VOLATILITY.NYSE-1-MINUTE-LAST-EXTERNAL` (assuming these are actually being aggregated externally by IB)?

This will be considered malformed. Now assuming these both are part of `PriceType` enums, it will be always follow the existing `BarType` string convension i.e `ABC.NYSE-1-MINUTE-HISTORICAL_VOLATILITY-EXTERNAL` or `ABC.NYSE-1-MINUTE-IMPLIED_VOLATILITY-EXTERNAL` - in case of external aggregation. _They can have `INTERNAL` aggregation when provided Historical Volatility Tick and Implied Volatility Tick data (as in the 2nd link Tick Id 23 and 24 relates to this). Just for information, that's not part of this PR._

> If we extended the `PriceType` then it opens up many code paths to error with the way its used throughout the core of the codebase. Or at least every 'switch' statement would have to be checked that its handling the invalid type cases (which would nearly always include these volatility types as being invalid).

True, it will be almost everywhere. It looks bit odd because of Enum's name `PriceType`, apart from this everything is perfect. Maybe this can have more suitable name to suit.

**Comment by cjdsellers** [comment]
Hi @rsmb7z 

To move forward on this, all things considered I don't think a volatility is a price type, but can be based on a price type (so should be separate).

How many different time frames for volatility would be appropriate? we could just make them different bar aggregations, e.g.
- `MINUTE_HISTORICAL_VOLATILITY`
- `HOUR_IMPLIED_VOLATILITY`

Having said that, the combination of the step and the `BarAggregation` becomes the _rule_ for bar formation. So in the case of the current time based bars, the bar is closed at the end of the time interval and represents a data event at `ts_event`. 

In this way, aren't implied volatility bars also an aggregation sampled across time? This leads me back to a previous suggestion`ABC-IMPLIED-VOLATILITY.NYSE-1-MINUTE-LAST-EXTERNAL`

So a bar type is `{INPUT}-{STEP}-{AGGREGATION/RULE}-{EXTERNAL/INTERNAL}`. The input in the above cases is the bid, ask, mid, last implied volatility across `step * time` intervals?

**Comment by cjdsellers** [comment]
Continuing discussion in https://github.com/nautechsystems/nautilus_trader/issues/970.

**Comment by cjdsellers** [comment]
Closing this for now was we decided in #970 that it's currently only applicable to IB.

**Pull request closed without merging**
