### PR TITLE
Wrap talib patterns recognition indicators

### PR DESCRIPTION
**Pull request by graceyangfan**
# Pull Request
wrap of the talib  candlestick patterns recognition indicators.(reference Issues #515 )
## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## How has this change been tested?
1.install talib
2.run nautilus_trader/tests/unit_tests/indicators/test_pattern.py

### CODE REVIEW

**Comment by cjdsellers** [comment]
Many thanks, and great idea. I just changed the base branch to `develop`.

I'll probably end up making talib an optional dependency.

**Comment by cjdsellers** [comment]
So this one is currently failing on

```
ModuleNotFoundError: No module named 'talib'
```

I've attempted to install several versions of TA-Lib onto a MacBook M1 (ARM64), without success:

```
thon3.framework/Versions/3.8/include/python3.8 -c talib/_ta_lib.c -o build/temp.macosx-10.14-arm64-3.8/talib/_ta_lib.o
      talib/_ta_lib.c:682:10: fatal error: 'ta-lib/ta_defs.h' file not found
      #include "ta-lib/ta_defs.h"
               ^~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command 'clang' failed with exit status 1
      [end of output]
```

Out of interest - what OS/platform are you on, and how did you install TA-Lib?

**Comment by graceyangfan** [comment]
@cjdsellers   I am using ta-lib at Ubuntu 20.04,and this error I have meet several times when I try to install talib.The right step to install talib is:(1）install talib source code with make tools (2)install talib python wrapper TA-Lib
here is my bash example:
`
#!/usr/bin/env bash
# Get and build ta-lib
function install-ta-lib()
{
    pushd /tmp
    wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    tar -xf ta-lib-0.4.0-src.tar.gz
    cd ta-lib
    ./configure --prefix=$prefix
    make -j1
    make install
    popd
}
function ta-lib-exists()
{
    ta-lib-config --libs > /dev/null
}
ta-lib-exists || install-ta-lib
# old versions of ta-lib imports numpy in setup.py
$python -m pip install numpy
# Install extra packages
$python -m pip install ta-lib
`

**Comment by cjdsellers** [comment]
I feel this could open up difficulties with installing `nautilus_trader`. Even if we made it an optional dependency, I still need to be able to test all code paths locally, including on macOS x86 and/or arm64. 

I'll have a think.

**Comment by limx0** [comment]
We could always just raise a warning if it's not installed like we currently do with docker for ib

**Pull request closed without merging**
