### PR TITLE
dt_to_unix_nanos_bug

### PR DESCRIPTION
**Pull request by limx0**

### CODE REVIEW

**Comment by crazy25000** [comment]
How can you reproduce this? I've been running into a strange date time issue where I get extra zeros, wonder if this is the same thing.

**Comment by limx0** [comment]
> How can you reproduce this? I've been running into a strange date time issue where I get extra zeros, wonder if this is the same thing.

@crazy25000 see https://github.com/nautechsystems/nautilus_trader/issues/384

**Comment by crazy25000** [comment]
> > How can you reproduce this? I've been running into a strange date time issue where I get extra zeros, wonder if this is the same thing.
> 
> @crazy25000 see #384

Slightly different than I thought. The strange dates I've seen were from `ts_opened` and `ts_closed` fields from a position report.

**Comment by limx0** [comment]
@crazy25000 haven't seen any issues with that - if you want to ping me on my email (in my profile) lets chat about it

**Comment by crazy25000** [comment]
@limx0 if I can reproduce it, will message you.

**Comment by limx0** [comment]
> @limx0 if I can reproduce it, will message you.

@crazy25000 we have a semi mailing list - ping me for details

**Comment by crazy25000** [comment]
Just sent you a message.

**Comment by cjdsellers** [comment]
Many thanks for finding and fixing!

**Pull request merged**
