### PR TITLE
Refine imports for type hints in Bybit

### PR DESCRIPTION
**Pull request by sunlei**
# Pull Request

Refine imports for type hints in Bybit.

## Type of change

Delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by cjdsellers — COMMENTED** [review]
Are we using `TYPE_CHECKING` for performance reasons here?
I'd be interested to know the improvements if you have any before-after figures.

**Comment by sunlei** [comment]
@cjdsellers 

I haven’t conducted performance tests for this specific scenario, but theoretically, it should be beneficial:

- Isolate type-checking code.
- Avoid unnecessary runtime imports.
- Reduce the likelihood of circular references.

**Comment by cjdsellers** [comment]
Sure, happy to merge - but thoughts are:

- We haven't experienced any circular import issues for Bybit, that I know of.
- Departs from the standard import patterns in most other Python modules.
- Could be considered boilerplate unless a strong reason for it?

A reason in favor is the potential runtime performance improvement, would be interesting to know because it could inform heading this way for other modules too.

**Comment by sunlei** [comment]
@cjdsellers 

Thank you!

- Bybit previously encountered a circular reference issue in one of its PRs, which I resolved using TYPE_CHECKING.
- I randomly checked two projects, PyTorch and Flask, and found that TYPE_CHECKING is used quite extensively.
- In my own projects, TYPE_CHECKING often serves as boilerplate code.

- For further reference:
  - https://mypy.readthedocs.io/en/stable/runtime_troubles.html

**Pull request merged**
