### PR TITLE
Fix timestamps in Interactive Brokers daily bars

### PR DESCRIPTION
**Pull request by benjaminsingleton**
# Pull Request

References #1353

## Type of change

Delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How has this change been tested?

Retrieved daily and non-daily (hourly, etc.) bars with success.

### CODE REVIEW

**Comment by cjdsellers** [comment]
Hi @benjaminsingleton 

Thanks for these changes, I think this looks great. My own preference is for time stamping bars on the close also - do you think we should make this configurable for the IB client though, and retain the default time stamping at the open by default?

We also have a config option `DataEngineConfig.time_bars_timestamp_on_close` which is related/in play here.

**Comment by benjaminsingleton** [comment]
The existing code actually only adjusts `ts_init` to reflect the closing timestamp while `ts_event` reflects the opening timestamp. By default, it should it be set the opposite way? For bars, does `ts_init` generally reflect the start of the bar period?

**Comment by benjaminsingleton** [comment]
The code here actually only adjusts `ts_init` to reflect the closing timestamp while `ts_event` reflects the opening timestamp. Am I correct that when running backtests / live data that the `DataEngineConfig.time_bars_timestamp_on_close` will take care of converting `ts_event` to the closing timestamp? If so, then I don't think we need to modify the code here.

**Comment by cjdsellers** [comment]
> Am I correct that when running backtests / live data that the `DataEngineConfig.time_bars_timestamp_on_close=True` will take care of converting `ts_event` to the closing timestamp? If so, then I don't think we need to modify the code here.

Correct, `True` is actually the default behavior - when `False` it will use the opening timestamp for `ts_event` (and `ts_init` is always close / object initialization).

I see, now that I've expanded all the code I see this is indeed just fixing the parsing for daily bars with no change to the `ts_init` timestamp adjustment - so I think this is correct as is too.

**Review by rsmb7z — APPROVED** [review]

**Comment by rsmb7z** [comment]
> We also have a config option `DataEngineConfig.time_bars_timestamp_on_close` which is related/in play here.

This flag is not in effect within the adapter, may be added. However current behavior is `ts_event` bar opening time and `ts_init` bar closing time (for historical) and actual time in case of live. New addition just supports the timestamp difference from IB following same.

**Comment by cjdsellers** [comment]
Thanks for the review @rsmb7z !

**Pull request merged**
