### PR TITLE
Add optional ping message

### PR DESCRIPTION
**Pull request by ayush-sb**
# Pull Request
- Add optional `message` field in WebSocketConfig
- Send either `Message::Ping` or `Message::Text` in `WebSocketClientInner::spawn_heartbeat_task` depending on presence of `message`

### CODE REVIEW

**Comment by filipmacek** [comment]
Looks alright. Can you also pls add tests for this

**Comment by ayush-sb** [comment]
Does adding tests here mean making one test with a `String` and one `None` for `message`?

**Comment by filipmacek** [comment]
Yeah, we want to test if the mock `TestServer` from [here](https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_core/network/src/websocket.rs#L523) is receiving correct ping messages. Maybe @twitu can help you with that

**Comment by twitu** [comment]
The changes look good. We just need to add a couple of tests and get it passing.
* You can verify the CI checks are passing locally by running `make pre-commit`
* The design is a bit complex but here's an overview. All the logic in the websocket.rs is for a websocket client only including the `spawn_read_task` and `spawn_heart_beat_task`. All the various parts create a client that can send hearbeats, send messages and reconnect if the connection breaks. All of these are automatically run and managed when a new websocket client is created, so these are not something that you need to change or manage in the tests. More details are here https://github.com/nautechsystems/nautilus_trader/issues/1098#issuecomment-1598206852
* The main logic to look into for adding a small new test is `impl TestServer`. So you can create a new server that stores the expected heartbeat message and when in the impl logic you can check for those messages.

**Pull request merged**
