### PR TITLE
Read (official) Binance headerless csv files

### LINKED ISSUE #500: Loading binance csv data
### Context
Hi, finally starting with nautilus trader, I am first trying to load data into a catalog.
I could notice that [backtest_config_example.ipynb](https://github.com/nautechsystems/nautilus_trader/blob/master/examples/backtest/notebooks/backtest_config_example.ipynb) is probably the best entry point.
However, I am adapting to the data I would like to use, which is 1minute bar data from Binance. I take data from Binance official repo, which is made available in csv.zip format [here](https://data.binance.vision).
In below example, I am more specifically starting with spot data, ADABTC pair, with monthly data for October 2021 (file [here](https://data.binance.vision/data/spot/monthly/klines/ADABTC/1m/ADABTC-1m-2021-10.zip)).

### Problem
Here is my current code. Basically, what should be the `block_parser` callable to be used in `CSVReader` is not so clear to me. I am providing a pre-configured `pd.read_csv` method for this, I get a `TypeError` exception.

### Steps to Reproduce the Problem

Code.
```python
import os, shutil
import pandas as pd
import numpy as np

from nautilus_trader.persistence.catalog import DataCatalog
from nautilus_trader.persistence.external.core import process_files, write_objects
# here, importing CSVReader, instead of TextReader
from nautilus_trader.persistence.external.readers import CSVReader

# here, importing Bar, instead of QuoteTick
from nautilus_trader.model.data.bar import Bar
# here, I have not yet checked what I should change :)
from nautilus_trader.model.objects import Price, Quantity

DATA_DIR = "~/Documents/code/data/binance/data/spot/monthly/klines/ADABTC/1m"
CATALOG_PATH = os.path.expanduser("~/Documents/code/data/nautilus_test/catalog")
if os.path.exists(CATALOG_PATH):
    shutil.rmtree(CATALOG_PATH)
os.makedirs(CATALOG_PATH)

ADABTC = TestInstrumentProvider.adabtc_binance()
catalog = DataCatalog(CATALOG_PATH)

# Pre-configured 'pd.read_csv()'
BINANCE_KLINES_CONF =  {'sep':',',
                                   'header':None,
                                   'names':('ts_open','open','high','low','close',
                                            'volume', 'ts_close', 'quote_volume',
                                            'n_trades', 'taker_buy_base_volume',
                                            'taker_buy_quote_volume', 'ignore'),
                                   'index_col':None, # no column to use as index
                                   'usecols':('ts_open','open','high','low','close',
                                              'volume', 'quote_volume'),
                                   'dtype':{'ts_open':np.int64,
                                            'open':np.float64,
                                            'high':np.float64,
                                            'low':np.float64,
                                            'close':np.float64,
                                            'volume':np.float64,
                                            'quote_volume':np.float64},
                                   'engine':'c',
                                   'compression':'zip'}

def parse_binance_klines(file):
    return pd.read_csv(file, **BINANCE_KLINES_CONF)

process_files(
    glob_path=f"{DATA_DIR}/*.zip",
    reader=CSVReader(block_parser=parse_binance_klines),
    catalog=catalog,
)
```
Error produced:
```python
[                                        ] | 0% Completed |  0.1s
Traceback (most recent call last):

  File "<ipython-input-19-24fcb10aed2f>", line 1, in <module>
    process_files(

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/nautilus_trader/persistence/external/core.py", line 132, in process_files
    results = compute(tasks)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 553, in get_sync
    return get_async(

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 496, in get_async
    for key, res_info, failed in queue_get(queue).result():

  File "/home/yoh/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()

  File "/home/yoh/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 538, in submit
    fut.set_result(fn(*args, **kwargs))

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 234, in batch_execute_tasks
    return [execute_task(*a) for a in it]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 234, in <listcomp>
    return [execute_task(*a) for a in it]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 225, in execute_task
    result = pack_exception(e, dumps)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/local.py", line 220, in execute_task
    result = _execute_task(task, data)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/dask/utils.py", line 37, in apply
    return func(*args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/nautilus_trader/persistence/external/core.py", line 103, in process_raw_file
    objs = [x for x in reader.parse(block) if x is not None]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/nautilus_trader/persistence/external/core.py", line 103, in <listcomp>
    objs = [x for x in reader.parse(block) if x is not None]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/nautilus_trader/persistence/external/readers.py", line 296, in parse
    yield from self.block_parser(chunk)

  File "<ipython-input-14-fcc5fbbbdee7>", line 2, in parse_binance_klines
    return pd.read_csv(file, **BINANCE_KLINES_CONF)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/common.py", line 585, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:

  File "/home/yoh/anaconda3/lib/python3.8/site-packages/pandas/io/common.py", line 962, in _is_binary_mode
    return isinstance(handle, binary_classes) or "b" in getattr(handle, "mode", mode)

TypeError: argument of type 'method' is not iterable
```

### Specifications

- OS Platform: Ubuntu 20.04
- NautilusTrader Version: `nautilus_trader.__version__ Out[22]: 'latest'`  ?

### PR DESCRIPTION
**Pull request by yohplala**
## Description
Starting with Nautilus trader, I will need data from Binance. I take them from official Binance repo, and Nautilus is not able to read them.
Well it is, if you tweak the call to `CSVReader`, initializing `header` attribute after `CSVReader` object is created, and it will work with only one csv file, as `header` attribute gets resetted to `None` at each new file being processed.

So what is it about?
 - official binance data file are headerless, data starts at the 1st row
 - current implementation expects the 1st row to contain the name of the columns, remove it to process the data, and use the column names to initialize dataframe column index.
 - once this 1st row is removed, file is parsed in chunks, and when 2nd data file starts, again, it removes the 1st row and so on...

This PR uncovers the `header` attribute so that it can be initialized when `CSVReader` class is instanced.
Logic is:
 - either `header` is set, and then `CSVReader` requires the csv file to be headerless
 - either `header` is not set (default value is `None`), and legacy behavior is retained (header retrieved from 1st row)

Fixes #500

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)        (somehow)
- [x] New feature (non-breaking change which adds functionality)      (somehow)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A: one added: `test_csv_reader_headless_dataframe` in `test_parsers.py`
- [x] Test B: all the other tests run with `poetry run pytest`. All those requiring a redis instance failing (I have no redis instance running :))

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Please, do not hesitate to share feedbacks if I am not following the style guidelines of the project. I try to replicate what I could see. Also, I have not seen new warnings, but I am not super expert in this.

### CODE REVIEW

**Comment by limx0** [comment]
Hi @yohplala - this looks very reasonable. +1

**Comment by yohplala** [comment]
> Hi @yohplala - this looks very reasonable. +1

super happy to make a 1st contribution! :)

**Comment by cjdsellers** [comment]
Hi @yohplala 

Thank you so much for this contribution, I had it in the back of my mind this would make things more flexible and usable.

It seems that the pre-commit step is failing on black formatting. Could you please run the following:

```
pre-commit install
make pre-commit
```
If you don't have make on your system, then this will also work:
```
pre-commit run --all-files
```
and then push the changes to this branch.

**Comment by yohplala** [comment]
Hi @cjdsellers 
Thanks, I did not know about `pre-commit`.
Here we are, it should be good now.

**Comment by cjdsellers** [comment]
Thanks for that, the pre-commit passed.

However CI has an issue with the `.zip` files. This has been an ongoing issue for us, and is the reason you'll notice there aren't many compressed files in the test data.

Would you be able to push again with plain CSV files, as small as possible to verify the parsing works correctly (as little as 10-20 rows should do).

**Comment by yohplala** [comment]
> Would you be able to push again with plain CSV files, as small as possible to verify the parsing works correctly (as little as 10-20 rows should do).

@cjdsellers   Ok, sorry, I shrank the csv file to about 21 rows total.
Sorry for the time taken for this small PR. Hope this time everything is ok.
(I have not yet carried over the changes to #503 , let's see if everything is now ok with this PR)

**Comment by yohplala** [comment]
Sidenote: you have write rights on my own remote nautilus repo? I am baffled. ahah :)

**Comment by cjdsellers** [comment]
Ah yes, well I'm able to push changes to the remote end of your feature branch. You still have to explicitly pull any of those changes back onto your local 😉

**Comment by cjdsellers** [comment]
Even more amazing is that this was being done from an iPad too, although normal Git commands can achieve the same thing.

Also something to note, because you haven't landed any changes onto the `develop` branch yet, I have to manually kick off the CI pipeline each time. Once this branch is merged, that won't be necessary and it'll happen when you push.

**Comment by yohplala** [comment]
Ok, I see some tests are failing, I will check deeper this evening. Please, don't lose time on this.
I have not updated the number of csv file that is checked by this test (from 11 to 13: I have added 2 csv files, this makes sense).
image

**Comment by cjdsellers** [comment]
That's OK, no rush - take your time.

**Comment by yohplala** [comment]
Today is the day! 

:)

**Pull request merged**
