### PR TITLE
Fix numpy-cython compatibility issue when using 32bit interpreter

### PR DESCRIPTION
**Pull request by ian-wazowski**

### CODE REVIEW

**Comment by ian-wazowski** [comment]
I will fix pre-commit failure

**Comment by cjdsellers** [comment]
Ok thanks

yea `poetry install`

and then `pre-commit install`

Will do the trick

**Comment by cjdsellers** [comment]
It looks good otherwise

**Comment by cjdsellers** [comment]
I need to merge something else, so on this occasion I'll accept and run pre-commit at my end

**Comment by cjdsellers** [comment]
It was just redundant parens around ```platform.architecture() == ("32bit", "WindowsPE")```
and a single redundant white space in a tuple.

About to push the fixes

**Comment by ian-wazowski** [comment]
@cjdsellers Thank you.

**Pull request merged**
