### PR TITLE
Add Multi-Instrument Rotation Trading Example with Controller for Binance

### PR DESCRIPTION
**Pull request by graceyangfan**
# Pull Request

This PR adds a new feature for Multi-Instrument Rotation Trading Example with Controller for Binance. The feature demonstrates how to manage multiple instruments and implement rotation strategies using the controller, extending the functionality of the project and providing users with a practical example for multi-instrument strategies. https://github.com/nautechsystems/nautilus_trader/issues/1936
@@limx0 @cuberone Thank you very much for your help. Please provide some suggestions.

## Type of change

Delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
## How has this change been tested?

This feature has been tested with Binance Testnet using simulated market data for multiple instruments to ensure that the rotation strategy works as expected.

### CODE REVIEW

**Comment by limx0** [comment]
Hi @graceyangfan - this looks like a great example to add!

The only minor improvement I would suggest is leveraging the cache (instruments and market data) for calculating your stats, so that the example would also work for backtesting purposes. But I think this can be added later.

**Comment by graceyangfan** [comment]
@limx0 You're absolutely right. This is indeed a great step towards what we're aiming for. To achieve consistency between live trading and backtesting in Nautilus, a few minor internal adjustments are still needed.

**Comment by graceyangfan** [comment]
In long-duration testing, it was discovered that there is still an issue with the code terminating automatically, without any obvious information. I need some time to troubleshoot and eliminate the bug.

**Comment by cjdsellers** [comment]
Hey @graceyangfan

Thanks for the contribution here!

In terms of CI, it looks like there's just some pre-commit issues.

You can run pre-commit locally with either:
```
make pre-commit
```
or
```
pre-commit run --all-files
```

It's also possible to install a git hook so that pre-commit runs automatically on every commit:
```
pre-commit install
```

Let me know if you need any further help :pray:.

**Comment by graceyangfan** [comment]
@cjdsellers  The current submitted version still has some issues, and I haven't had the time to thoroughly review it recently. If possible, I can close this pull request for now.

**Pull request closed without merging**
