### PR TITLE
Convert unittest tests to pytest (tests/unit_tests/indicators)

### PR DESCRIPTION
**Pull request by Shutchinson**
Issue Ticket: #325

The next batch PR for converting unittest to pytest

The following files have been converted (29 total):

- tests/unit_tests/indicators/*.py
- tests/unit_tests/live/test_live_data_engine.py

### CODE REVIEW

**Comment by cjdsellers** [comment]
Excellent work! Much appreciated :rocket:

**Comment by crazy25000** [comment]
Dang, I was updating the same tests locally.

**Comment by cjdsellers** [comment]
@crazy25000 ah thats frustrating, are there any others you're working on? I think @Shutchinson adn @pkkm and going through them all.

**Comment by crazy25000** [comment]
> @crazy25000 ah thats frustrating, are there any others you're working on? I think @Shutchinson adn @pkkm and going through them all.

Yeah, was surprised when I saw the merge conflicts :sweat: ....I started with the indicators folder, stopped working on them after seeing the other unit test updates. I'll look for another issue.

**Pull request merged**
