### PR TITLE
Implement ParquetTickLoader and Upload sample data.

### PR DESCRIPTION
**Pull request by ian-wazowski**
See [this](https://github.com/nautechsystems/nautilus_trader/issues/177)

### CODE REVIEW

**Comment by cjdsellers** [comment]
Ok, run the command `poetry update` as whenever the `pyproject.toml` has dependencies added poetry must regenerate the `poetry.lock` file.

Also a good idea to get pre-commit up and running to ensure all the auto linting runs.

**Comment by ian-wazowski** [comment]
> Ok, run the command `poetry update` as whenever the `pyproject.toml` has dependencies added poetry must regenerate the `poetry.lock` file.
> 
> Also a good idea to get pre-commit up and running to ensure all the auto linting runs.
> 
> Both poetry and pre-commit are easy installs and all the config they need is in nautilus_trader.

Ok, Done

Thanks!

**Comment by cjdsellers** [comment]
Strange error, it seems to be using incorrect versions of packages for some reason.

**Comment by cjdsellers** [comment]
I'm actually going to merge this and fix on my end. 

Are you happy to sign the CLA?

**Comment by ian-wazowski** [comment]
> Strange error, it seems to be using incorrect versions of packages for some reason.

Oh... I will check it

**Comment by cjdsellers** [comment]
Just a question though, how are you using pynvim?

**Comment by ian-wazowski** [comment]
> Just a question though, how are you using pynvim?

https://vim.fisadev.com/

**Comment by cjdsellers** [comment]
It does look pretty awesome, however it's probably more appropriate to your own environment rather than bringing it into the package dependencies. If it was needed for parquet that would be different, so I'll probably remove that dependency.

**Comment by cjdsellers** [comment]
This is the issue

https://stackoverflow.com/questions/64949384/cant-install-pyarrow-on-osx-python-3-9-is-this-me-or-an-incompatible-package

**Comment by cjdsellers** [comment]
For the merged changes which would fix this.

"We'll release them in 2021-01."

**Comment by cjdsellers** [comment]
I can potentially do something here with a temporary nox session which only tests parquet on compatible versions. I'll let you know.

**Comment by ian-wazowski** [comment]
> For the merged changes which would fix this.
> 
> "We'll release them in 2021-01."

I saw that too, They are working on it.

> I can potentially do something here with a temporary nox session which only tests parquet on compatible versions. I'll let you know.

Ok, Thanks!

**Comment by cjdsellers** [comment]
Bleeding edge stuff this :)

**Comment by cjdsellers** [comment]
Actually all they need is

```
@pytest.mark.skipif(sys.version_info >= (3, 9), reason="requires python < 3.9")
```

and in the `pyproject.toml`

```
pyarrow = { version = "^2.0.0", python = "<3.9" }
```

Will push soon.

**Comment by cjdsellers** [comment]
For what its worth I changed the coverage to run in Python 3.8, so we'll still get the test coverage. 

`# TODO`s to remind us to return everything to normal once they release the wheels for Python 3.9.

I'm sure it won't be long, please let me know when they do.

**Comment by ian-wazowski** [comment]
> For what its worth I changed the coverage to run in Python 3.8, so we'll still get the test coverage.
> 
> `# TODO`s to remind us to return everything to normal once they release the wheels for Python 3.9.
> 
> I'm sure it won't be long, please let me know when they do.

yes, I will remove TODOs ASAP and I'll let you know when they done their pypi build.

**Pull request merged**
